# Generated by Django 2.2.4 on 2019-08-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190823_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdRating',
            new_name='imdbRating',
        ),
    ]
